name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs: 
  scan-and-deploy:
    runs-on: self-hosted

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bandit (Python SAST)
        run: |
          pip install bandit --break-system-packages
          ~/.local/bin/bandit -r app/ -ll

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build container image
        run: |
          docker build -t ghcr.io/acalebratliff/hello-app:latest .

      - name: Run Trivy (container scan)
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL ghcr.io/acalebratliff/hello-app:latest

      - name: Push image to ghcr.io
        run: |
          docker push ghcr.io/acalebratliff/hello-app:latest

      - name: Run Checkov (IaC scan)
        run: |
          pip install checkov --break-system-packages
          ~/.local/bin/checkov -d k8s/ --framework kubernetes --skip-check CKV_K8S_14,CKV_K8S_43,CKV_K8S_21

      - name: Deploy to k3s
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/ 